name: hsbf
version: 0.1.1
github: "leonardoarroyo/hsbf"
license: BSD3
author: "Leonardo Arroyo"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/leonardoarroyo/hsbf#readme>

dependencies:
  - base >= 4.7 && < 5
  - mtl
  - containers
  - lens
  - deepseq
  - random
  - array
  - monad-loops
  - parsec
  - HUnit
  - smallcheck
  - QuickCheck
  - tasty
  - tasty-hunit
  - tasty-smallcheck
  - tasty-quickcheck
  - cond
  - optparse-applicative
  - directory
  - paths
  - safe

library:
  source-dirs: src

executables:
  hsbf:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hsbf
      - mtl
      - containers
      - lens
      - deepseq
      - random
      - array
      - monad-loops
      - parsec
      - cond
      - optparse-applicative
      - paths
      - directory
      - safe

tests:
  hsbf-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hsbf
      - HUnit
      - smallcheck
      - QuickCheck
      - tasty
      - tasty-hunit
      - tasty-smallcheck
      - tasty-quickcheck
      - safe
