on:
  push:
    tags:
      - "v*.*.*"
name: release
jobs:
  release:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: "8.10.4"
          enable-stack: true
          stack-version: "latest"
      - run: stack test
      - run: stack build
      - run: cp "$(stack path --local-install-root)/bin/hsbf" ./hsbf-linux-amd64
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: hsbf-linux-amd64
